[buildPlans.afio]
family = "afio"
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

[buildPlans.afio.variants]
iherits = "ss15"

[buildPlans.afio.variants.design]
five = "upright-arched-serifless"
six = "straight-bar"
seven = "straight-serifless"
nine = "straight-bar"
zero = "tall-slashed"
capital-d = "standard-serifless"
capital-g = "toothed-inward-serifed-hookless"
capital-j = "serifed-both-sides"
capital-m = "flat-bottom-serifless"
capital-q = "crossing"
capital-u = "toothed-serifless"
capital-w = "straight-flat-top-serifless"
a = "double-storey-tailed"
e = "flat-crossbar"
g = "single-storey-serifless"
i = "serifed-asymmetric"
j = "flat-hook-serifed"
m = "serifless"
r = "serifed"
brace = "straight"
number-sign = "slanted"
at = "fourfold"
dollar = "through-cap"
percent = "rings-continuous-slash"
question = "smooth"
pilcrow = "high"
lig-ltgteq = "slanted"
lig-single-arrow-bar = "without-notch"

[buildPlans.afio.variants.italic]
five = "upright-arched-serifless"
six = "straight-bar"
seven = "straight-serifless"
zero = "tall-slashed"
capital-d = "standard-serifless"
capital-g = "toothed-inward-serifed-hookless"
capital-j = "serifed-both-sides"
capital-m = "flat-bottom-serifless"
capital-q = "crossing"
capital-w = "straight-flat-top-serifless"
a = "double-storey-tailed"
f = "tailed"
g = "single-storey-serifless"
i = "serifed-diagonal-tailed"
j = "flat-hook-serifed"
m = "serifless"
r = "corner-hooked-serifed"
v = "straight-motion-serifed"
w = "straight-flat-top-motion-serifed"
x = "straight-bilateral-motion-serifed"
y = "straight-turn-motion-serifed"
z = "straight-serifless"
brace = "straight"
number-sign = "slanted"
at = "fourfold"
dollar = "through-cap"
percent = "rings-continuous-slash"
question = "smooth"
pilcrow = "high"
lig-ltgteq = "slanted"

[buildPlans.afio.weights.light]
shape = 200
menu  = 300
css   = 300

[buildPlans.afio.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.afio.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.afio.widths.SemiCondensed]
shape = 456
menu = 4
css = "semi-condensed"

[buildPlans.afio.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.afio.widths.ExtraExtended]
shape = 658
menu = 8
css = "extra-expanded"

[buildPlans.afio.widths.UltraExtended]
shape = 720
menu = 9
css = "ultra-expanded"

[buildPlans.afio.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.afio.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.afio.slants]
upright = "normal"
italic = "italic"
# oblique = "oblique"

[buildPlans.afio.widths.normal]
shape = 500        # Width grade of glyph shapes. NOT actual character width.
menu  = 5          # Width grade for the font's names. NOT actual character width.
css   = "normal"   # "font-stretch' property of webfont CSS.
